name: football-player-reid-cpu
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.21.0
  - scipy>=1.7.0
  - opencv>=4.5.0
  - pillow>=8.3.0
  - matplotlib>=3.4.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - scikit-image>=0.18.0
  - tqdm>=4.62.0
  - pytorch>=1.12.0
  - torchvision>=0.13.0
  - cpuonly  # CPU-only PyTorch
  - pip:
    - ultralytics==8.0.20
    - deep-sort-realtime>=1.2.0
    - pytest>=6.2.0
    - pytest-cov>=2.12.0
    - black>=21.9.0
    - flake8>=3.9.0 